services:
  # Web service
  - type: web
    name: web-analyzer-service
    env: docker
    region: oregon
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /health
    routes:
      - type: rewrite
        source: /api/v1/*
        destination: /api/v1/$1
      - type: rewrite
        source: /health
        destination: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: MAX_WORKERS
        value: 4
      - key: NLTK_DATA
        value: /app/nltk_data
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1