services:
  # Web service
  - type: web
    name: web-analyzer-service-v2
    env: docker
    region: oregon
    plan: starter
    branch: master
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_WORKERS
        value: 4
      - key: NLTK_DATA
        value: /app/nltk_data
      - key: PYTHONUNBUFFERED
        value: 1
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1