# Male body shapes
- triangle body shape
- triangle shape
- pear shape
- inverted triangle
- inverted triangle body shape
- v-shape
- athletic
- athletic build
- rectangle
- rectangle body shape
- straight
- oval
- oval body shape
- round
- apple shape
- apple body shape
- trapezoid
- trapezoid body shape

# Body features
- broad shoulders
- narrow shoulders
- muscular chest
- muscular build
- slim waist
- narrow waist
- wide waist
- full waist
- slim hips
- narrow hips
- wide hips
- full hips
- short legs
- long legs
- slim legs
- muscular legs
- long torso
- short torso 