# Tops
- oxford shirt
- dress shirt
- button-down shirt
- polo shirt
- t-shirt
- tee
- henley shirt
- sweater
- jumper
- cardigan
- pullover
- sweatshirt
- hoodie
- tank top
- vest
- waistcoat
- navy blazer
- sport coat
- suit jacket
- dinner jacket
- double breasted suit jacket
- single breasted suit jacket
- tweed jacket
- harrington jacket
- field jacket
- safari jacket
- gilet
- puffer vest

# Bottoms
- khaki trousers
- dress trousers
- chinos
- preppy chinos
- jeans
- denim jeans
- corduroy trousers
- joggers
- sweatpants
- shorts
- bermuda shorts
- swim shorts
- formal trousers
- casual trousers
- pleated trousers
- flat front trousers

# Outerwear
- overcoat
- topcoat
- trench coat
- raincoat
- mac
- parka
- anorak
- windbreaker
- peacoat
- duffle coat
- leather jacket
- bomber jacket
- harrington jacket # Duplicate, acceptable
- field jacket # Duplicate, acceptable
- safari jacket # Duplicate, acceptable
- gilet # Duplicate, acceptable
- puffer vest # Duplicate, acceptable

# Footwear
- oxford shoes
- derby shoes
- brogues
- penny loafers
- boat shoes
- deck shoes
- driving shoes
- monk strap shoes
- chelsea boots
- desert boots
- chukka boots
- wingtip shoes
- moccasins
- sneakers
- trainers
- sandals
- espadrilles
- slippers
- dress shoes
- formal shoes
- casual shoes

# Accessories
- necktie
- tie
- bow tie
- pocket square
- cufflinks
- tie bar
- tie clip
- belt
- suspenders
- braces
- watch
- scarf
- gloves
- hat
- cap
- beanie
- sunglasses
- wallet
- briefcase
- messenger bag
- backpack
- umbrella
- socks

# Full outfits
- suit
- tuxedo
- dinner suit
- three-piece suit
- two-piece suit
- ensemble
- outfit
- look
- attire
- formal attire
- business attire
- casual attire 