# Basic colours
- navy
- navy blue
- blue
- light blue
- sky blue
- cobalt blue
- royal blue
- white
- off-white
- cream
- ivory
- eggshell
- grey
- gray
- charcoal
- silver
- black
- red
- burgundy
- maroon
- green
- olive
- forest green
- khaki
- beige
- tan
- brown
- chocolate brown
- camel
- pink
- purple
- lavender
- orange
- coral
- yellow
- gold
- mustard

# Seasonal colour analysis terms
- spring colours
- summer colours
- autumn colours
- winter colours
- warm colours
- cool colours
- clear colours
- muted colours
- deep colours
- light colours
- dark colours
- bright colours
- soft colours
- neutral colours
- earthy colours
- pastel colours
- jewel tones
- monochrome
- tonal

# Specific seasonal palettes
- true spring
- light spring
- bright spring
- warm spring
- true summer
- light summer
- soft summer
- cool summer
- true autumn
- soft autumn
- deep autumn
- warm autumn
- true winter
- deep winter
- clear winter
- cool winter

# Old money colours
- old money colours
- heritage colours
- traditional colours
- preppy colours
- ivy league colours
- collegiate colours
- nautical colours 