# Luxury/high-end brands
- ralph lauren
- polo ralph lauren
- brooks brothers
- j.press
- drakes
- barbour
- burberry
- lacoste
- hugo boss
- vineyard vines
- j.crew
- sperry
- loro piana
- brunello cucinelli
- zegna
- tom ford
- gucci
- prada
- louis vuitton
- hermes
- armani
- versace
- charles tyrwhitt
- thomas pink
- hackett london
- turnbull & asser
- brioni

# Old money associated brands
- lululemon
- l.l.bean
- bean boots
- duck boots
- patagonia
- north face
- orvis
- filson
- pendleton
- woolrich
- hunter boots
- belstaff
- gant
- johnston & murphy
- allen edmonds
- tricker's
- crockett & jones
- church's
- alden
- new balance
- keds
- sebago
- sperrys
- quoddy

# Fast fashion brands
- uniqlo
- h&m
- zara
- massimo dutti
- mango
- topman
- cos
- arket
- gap
- banana republic
- old navy
- express
- asos
- everlane
- reiss
- sandro
- maje
- club monaco
- suitsupply 