# Natural fibers
- cotton
- pima cotton
- sea island cotton
- egyptian cotton
- supima
- wool
- merino wool
- lambswool
- shetland wool
- cashmere
- tweed
- houndstooth
- herringbone
- linen
- flax
- silk
- mohair
- alpaca
- camel hair
- vicuña
- leather
- suede
- nubuck
- calfskin
- cordovan
- sheepskin
- deerskin
- pigskin
- sharkskin
- alligator
- crocodile

# Synthetic and mixed fibers
- polyester
- nylon
- acrylic
- rayon
- viscose
- tencel
- lycra
- spandex
- elastane
- gore-tex
- performance fabric
- tech fabric
- microfiber
- fleece
- down
- goose down
- duck down
- synthetic down

# Weaves and treatments
- oxford cloth
- broadcloth
- poplin
- twill
- pinpoint
- chambray
- denim
- seersucker
- corduroy
- madras
- flannel
- gabardine
- canvas
- velvet
- velour
- waxed
- weatherproof
- waterproof
- breathable 