# Seasons
- spring
- summer
- autumn
- fall
- winter
- seasonal
- year-round
- trans-seasonal
- resort
- vacation
- holiday

# Weather conditions
- warm weather
- cold weather
- hot weather
- cool weather
- rainy
- wet weather
- sunny
- windy
- humid
- dry
- temperate

# Seasonal activities
- beach
- coastal
- skiing
- winter sports
- summer sports
- outdoor
- indoor
- layering
- temperature regulation
- weather-appropriate 