# Traditional/conservative styles
- old money style
- old money fashion
- ivy league style
- preppy style
- trad style
- traditional style
- conservative style
- classic style
- heritage style
- vintage style
- retro style
- smart style
- formal style
- business casual
- casual style
- smart casual
- business formal
- black tie
- white tie
- cocktail attire
- evening wear

# Regional styles
- american traditional
- british style
- italian style
- french style
- scandinavian style
- japanese style
- korean style
- nautical style
- coastal style
- country style
- rural style
- urban style
- ivy style
- british countryside
- english country
- scottish highland
- italian sprezzatura
- parisian style
- riviera style
- mediterranean style
- alpine style
- cape cod style
- nantucket style
- hamptons style
- upper east side
- roppongi hills
- sloane ranger
- kensington style
- chelsea style
- mayfair style

# Contemporary styles
- minimalist style
- capsule wardrobe
- streetwear
- athleisure
- techwear
- workwear
- utility style
- avant-garde
- contemporary style
- modern style
- clean-cut style
- smart style # Duplicate, acceptable
- sharp style
- polished style
- refined style
- new money style
- luxury style
- high-end style
- punk style
- goth style
- boho chic
- bcbg style 